package com.daily.analysis.model.pojo;

public class AnaConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.conf_id
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private Integer confId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.server_ip
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private String serverIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.snort_conf_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private String snortConfUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.server_username
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private String serverUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.server_password
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private String serverPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.server_name
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private String serverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.snort_rule_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private String snortRuleUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.guarduan_conf_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private String guarduanConfUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.alert_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private String alertUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.alert_default_line
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private Integer alertDefaultLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.guardian_log_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private String guardianLogUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.snort_start_cmd
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private String snortStartCmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.snort_stop_cmd
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private String snortStopCmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.snort_log_default_line
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private Integer snortLogDefaultLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.guardian_start_cmd
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private String guardianStartCmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.guardian_stop_cmd
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private String guardianStopCmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.guardian_log_default_line
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    private Integer guardianLogDefaultLine;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.conf_id
     *
     * @return the value of ana_config.conf_id
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public Integer getConfId() {
        return confId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.conf_id
     *
     * @param confId the value for ana_config.conf_id
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setConfId(Integer confId) {
        this.confId = confId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.server_ip
     *
     * @return the value of ana_config.server_ip
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.server_ip
     *
     * @param serverIp the value for ana_config.server_ip
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp == null ? null : serverIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.snort_conf_url
     *
     * @return the value of ana_config.snort_conf_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public String getSnortConfUrl() {
        return snortConfUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.snort_conf_url
     *
     * @param snortConfUrl the value for ana_config.snort_conf_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setSnortConfUrl(String snortConfUrl) {
        this.snortConfUrl = snortConfUrl == null ? null : snortConfUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.server_username
     *
     * @return the value of ana_config.server_username
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public String getServerUsername() {
        return serverUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.server_username
     *
     * @param serverUsername the value for ana_config.server_username
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setServerUsername(String serverUsername) {
        this.serverUsername = serverUsername == null ? null : serverUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.server_password
     *
     * @return the value of ana_config.server_password
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public String getServerPassword() {
        return serverPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.server_password
     *
     * @param serverPassword the value for ana_config.server_password
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setServerPassword(String serverPassword) {
        this.serverPassword = serverPassword == null ? null : serverPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.server_name
     *
     * @return the value of ana_config.server_name
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.server_name
     *
     * @param serverName the value for ana_config.server_name
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setServerName(String serverName) {
        this.serverName = serverName == null ? null : serverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.snort_rule_url
     *
     * @return the value of ana_config.snort_rule_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public String getSnortRuleUrl() {
        return snortRuleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.snort_rule_url
     *
     * @param snortRuleUrl the value for ana_config.snort_rule_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setSnortRuleUrl(String snortRuleUrl) {
        this.snortRuleUrl = snortRuleUrl == null ? null : snortRuleUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.guarduan_conf_url
     *
     * @return the value of ana_config.guarduan_conf_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public String getGuarduanConfUrl() {
        return guarduanConfUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.guarduan_conf_url
     *
     * @param guarduanConfUrl the value for ana_config.guarduan_conf_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setGuarduanConfUrl(String guarduanConfUrl) {
        this.guarduanConfUrl = guarduanConfUrl == null ? null : guarduanConfUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.alert_url
     *
     * @return the value of ana_config.alert_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public String getAlertUrl() {
        return alertUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.alert_url
     *
     * @param alertUrl the value for ana_config.alert_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setAlertUrl(String alertUrl) {
        this.alertUrl = alertUrl == null ? null : alertUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.alert_default_line
     *
     * @return the value of ana_config.alert_default_line
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public Integer getAlertDefaultLine() {
        return alertDefaultLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.alert_default_line
     *
     * @param alertDefaultLine the value for ana_config.alert_default_line
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setAlertDefaultLine(Integer alertDefaultLine) {
        this.alertDefaultLine = alertDefaultLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.guardian_log_url
     *
     * @return the value of ana_config.guardian_log_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public String getGuardianLogUrl() {
        return guardianLogUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.guardian_log_url
     *
     * @param guardianLogUrl the value for ana_config.guardian_log_url
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setGuardianLogUrl(String guardianLogUrl) {
        this.guardianLogUrl = guardianLogUrl == null ? null : guardianLogUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.snort_start_cmd
     *
     * @return the value of ana_config.snort_start_cmd
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public String getSnortStartCmd() {
        return snortStartCmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.snort_start_cmd
     *
     * @param snortStartCmd the value for ana_config.snort_start_cmd
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setSnortStartCmd(String snortStartCmd) {
        this.snortStartCmd = snortStartCmd == null ? null : snortStartCmd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.snort_stop_cmd
     *
     * @return the value of ana_config.snort_stop_cmd
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public String getSnortStopCmd() {
        return snortStopCmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.snort_stop_cmd
     *
     * @param snortStopCmd the value for ana_config.snort_stop_cmd
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setSnortStopCmd(String snortStopCmd) {
        this.snortStopCmd = snortStopCmd == null ? null : snortStopCmd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.snort_log_default_line
     *
     * @return the value of ana_config.snort_log_default_line
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public Integer getSnortLogDefaultLine() {
        return snortLogDefaultLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.snort_log_default_line
     *
     * @param snortLogDefaultLine the value for ana_config.snort_log_default_line
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setSnortLogDefaultLine(Integer snortLogDefaultLine) {
        this.snortLogDefaultLine = snortLogDefaultLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.guardian_start_cmd
     *
     * @return the value of ana_config.guardian_start_cmd
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public String getGuardianStartCmd() {
        return guardianStartCmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.guardian_start_cmd
     *
     * @param guardianStartCmd the value for ana_config.guardian_start_cmd
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setGuardianStartCmd(String guardianStartCmd) {
        this.guardianStartCmd = guardianStartCmd == null ? null : guardianStartCmd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.guardian_stop_cmd
     *
     * @return the value of ana_config.guardian_stop_cmd
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public String getGuardianStopCmd() {
        return guardianStopCmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.guardian_stop_cmd
     *
     * @param guardianStopCmd the value for ana_config.guardian_stop_cmd
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setGuardianStopCmd(String guardianStopCmd) {
        this.guardianStopCmd = guardianStopCmd == null ? null : guardianStopCmd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.guardian_log_default_line
     *
     * @return the value of ana_config.guardian_log_default_line
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public Integer getGuardianLogDefaultLine() {
        return guardianLogDefaultLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.guardian_log_default_line
     *
     * @param guardianLogDefaultLine the value for ana_config.guardian_log_default_line
     *
     * @mbggenerated Sun May 31 23:50:54 CST 2015
     */
    public void setGuardianLogDefaultLine(Integer guardianLogDefaultLine) {
        this.guardianLogDefaultLine = guardianLogDefaultLine;
    }
}