package com.daily.analysis.model.pojo;

public class AnaConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.conf_id
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    private Integer confId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.server_ip
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    private String serverIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.snort_conf_url
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    private String snortConfUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.server_username
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    private String serverUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.server_password
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    private String serverPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ana_config.server_name
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    private String serverName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.conf_id
     *
     * @return the value of ana_config.conf_id
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    public Integer getConfId() {
        return confId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.conf_id
     *
     * @param confId the value for ana_config.conf_id
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    public void setConfId(Integer confId) {
        this.confId = confId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.server_ip
     *
     * @return the value of ana_config.server_ip
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.server_ip
     *
     * @param serverIp the value for ana_config.server_ip
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp == null ? null : serverIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.snort_conf_url
     *
     * @return the value of ana_config.snort_conf_url
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    public String getSnortConfUrl() {
        return snortConfUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.snort_conf_url
     *
     * @param snortConfUrl the value for ana_config.snort_conf_url
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    public void setSnortConfUrl(String snortConfUrl) {
        this.snortConfUrl = snortConfUrl == null ? null : snortConfUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.server_username
     *
     * @return the value of ana_config.server_username
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    public String getServerUsername() {
        return serverUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.server_username
     *
     * @param serverUsername the value for ana_config.server_username
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    public void setServerUsername(String serverUsername) {
        this.serverUsername = serverUsername == null ? null : serverUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.server_password
     *
     * @return the value of ana_config.server_password
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    public String getServerPassword() {
        return serverPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.server_password
     *
     * @param serverPassword the value for ana_config.server_password
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    public void setServerPassword(String serverPassword) {
        this.serverPassword = serverPassword == null ? null : serverPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ana_config.server_name
     *
     * @return the value of ana_config.server_name
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ana_config.server_name
     *
     * @param serverName the value for ana_config.server_name
     *
     * @mbggenerated Sat May 23 02:04:57 CST 2015
     */
    public void setServerName(String serverName) {
        this.serverName = serverName == null ? null : serverName.trim();
    }
}