package com.daily.analysis.model.pojo;

import java.util.Date;

public class TestUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.id
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.name
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.age
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    private Byte age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.birth
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.create_time
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.id
     *
     * @return the value of test_user.id
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.id
     *
     * @param id the value for test_user.id
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.name
     *
     * @return the value of test_user.name
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.name
     *
     * @param name the value for test_user.name
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.age
     *
     * @return the value of test_user.age
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.age
     *
     * @param age the value for test_user.age
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.birth
     *
     * @return the value of test_user.birth
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.birth
     *
     * @param birth the value for test_user.birth
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.create_time
     *
     * @return the value of test_user.create_time
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.create_time
     *
     * @param createTime the value for test_user.create_time
     *
     * @mbggenerated Wed May 13 15:33:19 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}